### PR TITLE
Allow custom styles and blocks

### PR DESCRIPTION
**Pull request by theozaurus**
It would be brilliant if inline styles and block types could be injected in so that React components which will just work are automatically generated for these additional styles and block types.

### CODE REVIEW

**Comment by jasonphillips** [comment]
Great idea. Once I have a moment to write in a new test case to cover this feature, as well as an update to the README, I'll be merging this in.

**Comment by jasonphillips** [comment]
I've been waiting off a bit on this idea to see how the plugins API settles in `draft-js-plugins`, which is still undergoing some revisions towards their full 2.0 release. I may check into it again very soon; I tried several variations on what you started in this PR, and some minor issues keep me from being able to commit to the approach, mainly concerning the way the plugins API currently works.

**Comment by Radivarig** [comment]
Looking forward to see this stable and merged.

**Comment by jasonphillips** [comment]
Thanks for the work here -- I have now published an update allowing for custom blocks and styles; see the updated demo & example code at `/example/CustomBlocksAndStyles.js`. In the end I took a slightly different approach from that submitted in this PR, but with the same general aim.

**Comment by theozaurus** [comment]
Brilliant. Thanks very much.

**Pull request closed without merging**
